### ISSUE TITLE
Editor is not loading, even for a new DNN installation

### ISSUE THREAD

**Issue by snstar2006** [w8tcha/dnnckeditor#11]
I tried the editor in a brand new DNN installation, but it seems like there are some files missing in the installation file. These three folders: XMLTemplates, iframedislog, and ajax are missing. And when a HTML is opened, the editor is not loading and only a loading image showing spinning for eternity. I copied these three folders from an old site that has CK Editor installed, and then the editor is working now. Why is there files missing?

**Comment by w8tcha** [comment]
thanks i updated the download packages with the missing plugins

**Comment by snstar2006** [comment]
Which one did you updated? I just downloaded 2.1.9 and install the module in a new DNN instance, and even more folders seems to be missing?

**Comment by w8tcha** [comment]
i dont know why this keep continue happening that the CKBuilder removes plugins.  i uploaded 2.1.9 again this time atleast it works for me..
