### ISSUE TITLE
Added Option to automatically resize Images on Quick Upload not working

### ISSUE THREAD

**Issue by denisjoconnor** [w8tcha/dnnckeditor#12]
Added Option to automatically resize Images on Quick Upload not working

**Details:**
In the Settings in the Config Tab is a new Setting ResizeImageQuality this enables the autom. Resizing The Settings Resize_MaxHeight and  Resize_MaxWidth will define when the image will be resized. If the width or height is bigger then defined it will be resized.
 
You can also reduce the file size via the Image Quality the Setting for that is ResizeImageQuality the default value is 80 (means 80%) so if you want to keep the image dimensions and only reduce the file size by decreasing the Quality you can do that.

The above added feature doesn't resize uploaded image but only adds styling of resize after being uploaded to server. Requirement needed is to resize on upload (save space on server) and set image size in same process and not to add resize styling only.

**Comment by w8tcha** [comment]
As far as i tested it works as expected. Did you actually enable the setting **ResizeImageOnQuickUpload**?

Did you test this with the quick upload in the link dialog or with the upload in the Filebrowser?

**Comment by denisjoconnor** [comment]
Hi Ingo,
My Quick Upload plugin licence has expired in fact. I will update it and retest, thanks

**Comment by w8tcha** [comment]
No you don't need a license. The quick upload is the upload tab inside the link dialog in the editor

**Comment by denisjoconnor** [comment]
I was referring to the jsplus addon 'Quick Image Upload' plugin but never checked the link dialog in the editor. Do you mean this:
![image](https://user-images.githubusercontent.com/16110075/30964331-c29f5c16-a448-11e7-9660-68a0bed6e5fa.png)

**Comment by w8tcha** [comment]
yes thats the quick upload function in the editor i mean.

**Comment by denisjoconnor** [comment]
Hi Ingo, OK I tried it just now and when I click 'OK' after uploading img it doesn't do anything?
![image](https://user-images.githubusercontent.com/16110075/30977691-3d85f1a2-a470-11e7-8060-36ea8b3d0114.png)
And this is the error when I click 'OK' - 
![image](https://user-images.githubusercontent.com/16110075/30977736-6269fc16-a470-11e7-92d4-ca3546079f0c.png)
I have this selected:
![image](https://user-images.githubusercontent.com/16110075/30977797-99a4922c-a470-11e7-806b-326a39167360.png)
And this is the before/after imgs file sizes:
855 KB (875,997 bytes)
22.2 KB (22,732 bytes)
so it appears to resize correctly just link dialog not working as I'd like
Thx

**Comment by w8tcha** [comment]
Yes i'm aware if the issue i just released version 2.1.10 of the editor provider. With the fixed link dialog.

**Comment by denisjoconnor** [comment]
Hi Ingo
That's great, thanks again!
