### ISSUE TITLE
Editor doesn't load on a page with two instances in Edge browser

### ISSUE THREAD

**Issue by sleupold** [w8tcha/dnnckeditor#13]
If you are having an edit page, where there are two HTML fields and the rich text editor should be loaded twice, no CK editor is displayed on first attempt, if using Microsoft Edge browser. (tested CKEditor provider 2.1.10 on DNN 7.4.2)

**Comment by w8tcha** [comment]
To reproduce the issue i need to know which what module this happens?

**Comment by sleupold** [comment]
I noticed this on DnnArticles from ZLDNN (http://store.dnnsoftware.com/home/product-details/dnnarticle-1011)

**Comment by w8tcha** [comment]
<img width="877" alt="editor" src="https://user-images.githubusercontent.com/722575/31014735-c5ff1db8-a51c-11e7-8430-bfc0992f7a32.PNG">

atleast with dnn 9 i cannot reproduce the issue with edge or ie11. Did you get any error messages in the browser console
