### ISSUE TITLE
Link dialog throws JS error, does not save and is too big

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#14]
Hi,

in dnn742.

The link dialog throws a js error upon opening:

```
Uncaught TypeError: Cannot read property '0' of null
    at CKEDITOR.dialog.onShow (link.js?t=H8DA:25)
    at CKEDITOR.dialog.n (ckeditor.js:10)
    at CKEDITOR.dialog.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:12)
    at CKEDITOR.dialog.<anonymous> (ckeditor.js:596)
    at ckeditor.js:28
```

The dialog self is too big, it contains "send email information", which is strange. 
Styling could be improved with a border around the dialog, in dialog.css e.g. :

```
.cke_dialog_body {
    z-index: 1;
    background: #fff;
    border: 1px solid #555555;
    border-radius: 5px;
    margin: 5px;
    padding: 2px;
}
```

Save / OK button does not work as well.

Thanks! Peter

**Comment by w8tcha** [comment]
This issue has already been fixed. Make sure you use the latest version, or if you already upgraded clear the browser cache in order to reload the js files
