### ISSUE TITLE
CKEditor not loading

### ISSUE THREAD

**Issue by muddeatr** [w8tcha/dnnckeditor#15]
Trying to edit an HTML module and the CKEditor just sits and displays the loading icon. Using the console debug shows the error below.

Error: [CKEDITOR.resourceManager.load] Resource name "iframedialog" was not found at "https://www.MYWEBSITE.com/Providers/HtmlEditorProviders/CKEditor/plugins/iframedialog/plugin.js?t=H8DA".

**Comment by w8tcha** [comment]
Are you using the latest version of the editor provider?

**Comment by muddeatr** [comment]
Yes, I first installed 2.01.09 then seen you had 2.01.10 so I installed that.

**Comment by w8tcha** [comment]
Did you cleared the browser cache after you upgraded to 02.01.10? otherwise the updated js files are not loaded

**Comment by muddeatr** [comment]
Yes. I even opened a different browser and refreshed that one as well.

**Comment by muddeatr** [comment]
So you close the issue without an explanation??

**Comment by w8tcha** [comment]
looks like there where 2 different plugins with similar name, i added the wrong one before. Now its included again

**Comment by muddeatr** [comment]
Is there a download available or should I add something to my files?

**Comment by w8tcha** [comment]
Yes i reuploaded version 2.1.10

**Comment by schotman** [comment]
The plugin iframedialog is missing from the release 2.1.11

**Comment by w8tcha** [comment]
i checked the ckeditor.js and the iframedialog plugin is included. did you clear the browser cache after upgrade?

**Comment by schotman** [comment]
I checked the file system, and it was missing. Adding the folder from another install and all is well again.
