### ISSUE TITLE
Suggested Upgrade Path

### ISSUE THREAD

**Issue by davegambino** [w8tcha/dnnckeditor#16]
I am currently using Version 2.0.7 on my DNN 7 Host.

I would like to upgrade to a more recent version but i am not sure what version I should upgrade to.

Can you provide any guidance as to an upgrade path and what versions may have substantial changes to the look and feel or functionality?

Thank you in advance for any help with this.

**Comment by w8tcha** [comment]
Did you do any customizations to the editor. I think you can directly upgrade to the latest version
