### ISSUE TITLE
mathjax shutdown

### ISSUE THREAD

**Issue by azarbara** [w8tcha/dnnckeditor#17]
Hey Ingo, 
the mathjax shut down in April. 
could you please change it [https://www.mathjax.org/](https://www.mathjax.org/), 
Or 
could you please add [Wiris](http://www.wiris.com/en/plugins/docs/ckeditor/dotnetnuke) extension to dnnCkeditor

**Comment by w8tcha** [comment]
i changed the CDN in 02.01.11
