### ISSUE TITLE
Embed button not visible on toolbar

### ISSUE THREAD

**Issue by lsilman** [w8tcha/dnnckeditor#18]
I've added the embed_provider as indicated [here](https://iframely.com/docs/ckeditor) and the embed button to the toolbar group settings, but it doesn't show, tried clearing the cache, refresh, new DNN install on local machine with same results. Using it on DNN 7.4.2.

Really appreciate any help, thanks!

**Comment by w8tcha** [comment]
I think there is a problem with the icons, can you post a screenshot of the editor?

**Comment by lsilman** [comment]
Thanks! screenshot attached, icon should be at the left of code snippet icon.
![dnnckeditor](https://user-images.githubusercontent.com/33167601/32147352-b063a270-bcab-11e7-8d45-f4c160d32296.jpg)

**Comment by w8tcha** [comment]
What happens when you click on the icon left next to the code snippet icon. At least for me the embed plug in has math plug in icon

**Comment by lsilman** [comment]
That opens the formula editor, screenshot attached.
![dnnckeditor](https://user-images.githubusercontent.com/33167601/32148831-9a44ec36-bcc1-11e7-863a-3e0bda7b8637.jpg)

**Comment by w8tcha** [comment]
Okay, so i guess its a different problem. Is the embed plugin in the list of extraPlugins in the Editor config? are you using the latest version of the Provider?

**Comment by lsilman** [comment]
Yes, it is on the ExtraPlugins field: embed,tableresize,textselection,notification,stylesheetparser,qrcodes,newsarticleslinks,codemirror,dnnpages,xmltemplates,wordcount

I installed 2.1.11 but said it was 2.1.10, so did a repair, still shows as 2.1.10.

**Comment by w8tcha** [comment]
I run out of ideas what could be the problem, i assume you loaded the correct toolbar?

You cab check in the browser console if the plugin if you enter 

CKEDITOR.instances.EDITORINSTANCE.plugins.embed

you need to replace editorinstance with your id the browser console should suggest you the correct id

**Comment by w8tcha** [comment]
any update?

**Comment by lsilman** [comment]
Yes! problem was in the CKToolbarSets.xml, the icon/plugin was being saved as `<ToolbarGroup><items><string>embed</string>...` , it works fine as `<ToolbarGroup><items><string>Embed</string>...`

Thanks and Happy Holidays!
