### ISSUE TITLE
Cannot set menu options Codesnippet

### ISSUE THREAD

**Issue by marietteknap** [w8tcha/dnnckeditor#19]
I am using latest version as of today and I cannot change the list of languages in the Code snippet plugin. I tried that from a CKCustom.js and load that within the provider but nothing happens. How do I change the list with languages?

**Comment by w8tcha** [comment]
this can only be done via a config setting

https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.config-cfg-codeSnippet_languages

If you need this i can add it to the config settings

**Comment by marietteknap** [comment]
![02-11-2017-11 41 36 00](https://user-images.githubusercontent.com/5551768/32321926-07832bba-bfc3-11e7-84a3-5192077d8e5a.png)
I thought one could set such settings in a Custom.js? Am I mistaken?

**Comment by marietteknap** [comment]
Yes, please add it to the config settings in the provider

**Comment by w8tcha** [comment]
No turns out the customConfig is ignored since all settings are not loaded via the config. But what you can do is use the  Custom JS option..

````js
CKEDITOR.on( 'instanceCreated', function( event ) {
 var editor = event.editor;

editor.on('configLoaded', function () {

editor.config.codeSnippet_languages = {
    javascript: 'JavaScript',
    php: 'PHP'
};
            });
} );
````

**Comment by marietteknap** [comment]
Very good, that works just fine.
