### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bradbamford** [w8tcha/dnnckeditor#2]
I'm still using this provider, but given DNN has forked this provider, what is the plan here moving forward?
Are there any benefits this provider has over DNN's?

**Comment by w8tcha** [comment]
Sorry but really exist no road map at the moment. I really don't have any free time. At the moment i only can try to fix bugs.

**Comment by bradbamford** [comment]
okay, and where will these bug fix releases be available, here or codeplex? 
I notice new check-ins here, but no release since 2016 at codeplex.

**Comment by w8tcha** [comment]
I moved the source repository to github. The last release was 4 month ago and will continue on CodePlex and also on GitHub. I fixed today most of the open issues. So the next bug fix release will be released in the next weeks.

Is there anything you need, or you ask in general?

**Comment by bradbamford** [comment]
Since Codeplex is shutting down, what's the release plan now?

**Comment by w8tcha** [comment]
Well nothing will change except no more releases on codeplex and all projects i need to move to GitHub. I already imported the CKEditor Dokumentation to GitHub https://github.com/w8tcha/dnnckeditor/wiki
