### ISSUE TITLE
Turn off basic editor

### ISSUE THREAD

**Issue by marietteknap** [w8tcha/dnnckeditor#20]
Like in the screenshot, how you turn the option for basic editor and rich editor off. I do not want to show that normal registered users or I want to completely turn it off.
![2017-11-03_19-12-14](https://user-images.githubusercontent.com/5551768/32389529-31b2adb2-c0cb-11e7-9919-37713e262e47.png)

**Comment by w8tcha** [comment]
The Radio list is rendered from within dnn not the editor provider, i think the only option would be to hide it via css
