### ISSUE TITLE
Recommended Image Crop and Resize Plugin

### ISSUE THREAD

**Issue by davegambino** [w8tcha/dnnckeditor#21]
Can you recommend the best Image Crop and resize plugin to use with the CKEditor?

Thank you.

**Comment by w8tcha** [comment]
You can use the build in functions of the file browser

https://camo.githubusercontent.com/d8a05dcd2f53f2f0867ea7ac9e714b637d202914/687474703a2f2f7777772e77617463686572736e65742e64652f506f7274616c732f302f73637265656e73686f74732f646e6e2f434b456469746f72496d616765456469746f722e6a7067

https://camo.githubusercontent.com/728a0639b88d931b1fa41c27b5de1902a4bfe27f/687474703a2f2f7777772e77617463686572736e65742e64652f506f7274616c732f302f73637265656e73686f74732f646e6e2f434b456469746f72496d616765456469746f72322e6a7067

**Comment by davegambino** [comment]
How do i install this plugin and configure this to work with the CkEditor?

**Comment by w8tcha** [comment]
1. Open the editor
2. click on the image icon in the editor toolbar.
3. Open the file browser via "Browse Server" 
4. Select the image you want to modiy
5. Click on the Edit image icon in the browser and it opens the resize modus as seen in the screenshot above.

**Comment by davegambino** [comment]
Thank you.  Are there any other plugins from this listing that are also compatible with your provider?

https://ckeditor.com/cke4/addons/plugins/all

**Comment by w8tcha** [comment]
Technically all plug-ins can be added. As described here

https://github.com/w8tcha/dnnckeditor/wiki/Add-a-Custom-Plugin

**Comment by davegambino** [comment]
Thank you.  One last question on this thread.  Can you tell me where to look in the CK Editor Documentation to know exactly what the result is of each setting on the Editor Config Tab? https://www.screencast.com/t/OOzr5Lx2

Is this the correct guide? https://docs.ckeditor.com/ckeditor4/latest/guide/index.html

**Comment by davegambino** [comment]
Also, which Upload Image Plugin are you referencing in this build 2.01.12 https://www.screencast.com/t/jNHOpefp

**Comment by w8tcha** [comment]
On top of the config tab is a link to the settings description page

https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html

**Comment by w8tcha** [comment]
There is online one image upload plug in, which was introduced in 4.8.0

https://ckeditor.com/cke4/addon/uploadimage

This plug in is included in the provider package

**Comment by davegambino** [comment]
But that page links to CKeditor 3.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by w8tcha** [comment]
> But that page links to CKeditor 3.

Yes but the settings are still valid in v4. But i update the link in the next release!
