### ISSUE TITLE
CKEditor wont load imgs and toolbar isnt displaying properly on firefox

### ISSUE THREAD

**Issue by denisjoconnor** [w8tcha/dnnckeditor#22]
When I click on a plugin it works but its icon is not displaying on Firefox v57.0 - 

![image](https://user-images.githubusercontent.com/16110075/33881788-cf381dda-df2d-11e7-975e-ae8ecd2e9c0c.png)
Also imgs I uploaded are not displaying?

![image](https://user-images.githubusercontent.com/16110075/33882017-9fcf5242-df2e-11e7-8e97-b480a5817f96.png)
NOTE: Both issues above work fine on Chrome - using latest release v02.01.11

**Comment by w8tcha** [comment]
Which theme (skin) for the editor did you use?

**Comment by denisjoconnor** [comment]
'moono-lisa' - 
![image](https://user-images.githubusercontent.com/16110075/33886272-ec8b3510-df3d-11e7-881e-048de22523c7.png)

**Comment by w8tcha** [comment]
both issue i cannot reproduce with firefox 57. Are you getting any issues in the browser console regarding the icons?

**Comment by w8tcha** [comment]
any update?
