### ISSUE TITLE
wrong page tree in link dialog in ML site

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#24]
in the link dialog:
link type --> portal page 

It shows the page tree of the main language and not the tree of the currently selected language. So working in Dutch I get the English page tree (and I would expect the Dutch page tree)

Core localization has been applied.

(BTW browse server dialog --> page link does show the correct page tree, so there is an easy work-a-round). 

Thanks!

**Comment by w8tcha** [comment]
Sorry i can not reproduce the issue in both cases it shows the same correct page links, when switching the languages. Also the code for both is equal so it should always display the same result

Its possible that you need to clear the browser cache after you change the language to refresh the js code.
