### ISSUE TITLE
Install aborted - An upgrade to version 8.4.0 is required.

### ISSUE THREAD

**Issue by djamell** [w8tcha/dnnckeditor#27]
I tried a fresh install of 2.01.12 on DNN 8.0.4 and I get the following error:

Failure | Install aborted - The module being installed  is not compatible with this version of DNN. An upgrade to version 8.4.0  is required.

Please Advise

**Comment by w8tcha** [comment]
sorry it should be 8.0.4 not 8.4.0! I updated the download packages
