### ISSUE TITLE
CKEditor 2.1.12 won't install in Evoq 8.5.0

### ISSUE THREAD

**Issue by moorecreative** [w8tcha/dnnckeditor#29]
This may perhaps be an issue with the editor going into Evoq edition vs community edition, however, during the install attempt, the first install screen displays the alert, "Error reading the zip package - see below." and:

"Install aborted - The module being installed is not compatible with this version of DNN. An upgrade to version 8.0.40 is required."

This is technically DNN Evoq 8.5.0 that I'm attempting to install into.

Is this a bug/issue? or proper incompatibility?

**Comment by w8tcha** [comment]
Sorry but Evoq is not supported only the Community Edition
