### ISSUE TITLE
CKEditor is loading please wait

### ISSUE THREAD

**Issue by GusBeare** [w8tcha/dnnckeditor#3]
Hi

I have a DNN8 site that I recently upgraded from 7.x.  I just got an issue that an error is raised when user tries to upload an image with the CKEditor.  I get this when they hit the browse server link:

dnn Unknown server tag 'dnn:DnnTreeView'.

So I tried upgrading to latest CKeditor package from here for DNN8 on a staging site.  But now the CKEditor hangs when loading.  "CKEditor is loading please wait".

In the chrome console I see:

Failed to load resource: the server responded with a status of 404 (Not Found)
plugin.js Failed to load resource: the server responded with a status of 404 (Not Found)
ckeditor.js:251 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "embed" was not found at "http://dev-site.dnn3-box.eu/Providers/HtmlEditorProviders/CKEditor/plugins/embed/plugin.js?t=H5SC".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:251)
    at f (ckeditor.js:246)
    at Array.C (ckeditor.js:246)
    at w (ckeditor.js:246)
    at ckeditor.js:247

Can you help?

**Comment by w8tcha** [comment]
Did you clear the browser cache after you upgraded? Otherwise the browser didn't reload the js files!

If this doesnt work try to  delete the CKEditor folder under Providers\HtmlEditorProviders\CKEditor, and then reinstall the provider

**Comment by GusBeare** [comment]
Since I hadn't heard I removed and re-installed and it works now. Thanks.
