### ISSUE TITLE
Installation Message

### ISSUE THREAD

**Issue by davegambino** [w8tcha/dnnckeditor#32]
I was attempting to install the the CKEditor Provider 2.01.13 https://github.com/w8tcha/dnnckeditor/releases/tag/v02.01.13

on a new DNN Host version 8.00.4 however, the installation stopped and gave an error message saying the Provider was not compatible with my version of DNN.  Please upgrade to DNN Version 8.4.  This was confusing because my version is DNN 8.4.

I then dropped to CKEditor Provider 2.01.12 and tried to install but got the same result with the error message.

Finally, i dropped to CKEditor Provider 2.01.11 and this version installed successfully.

Can you provide any guidance for me?

Thank you.

**Comment by w8tcha** [comment]
I updated the release 
https://github.com/w8tcha/dnnckeditor/releases/tag/v02.01.13

issue is fixed
