### ISSUE TITLE
Image Browser Fails on startup

### ISSUE THREAD

**Issue by rhunter27338** [w8tcha/dnnckeditor#35]
I just installed the CKEditor since I am getting a method error on the Telerik Rad Editor in DNN.  I installed 2.1.15 for the DNN9.2 version.

The error I receive is:
Value was either too large or too small for an Int32.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.OverflowException: Value was either too large or too small for an Int32.
[OverflowException: Value was either too large or too small for an Int32.]
   System.Convert.ToInt32(Int64 value) +12931011
   WatchersNET.CKEditor.Utilities.SettingsUtil.GetCurrentUserUploadSize(EditorProviderSettings settings, PortalSettings portalSettings, HttpRequest httpRequest) +56
   WatchersNET.CKEditor.Browser.Browser.Page_Load(Object sender, EventArgs e) +1114
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.Web.UI.Control.OnLoad(EventArgs e) +95
   System.Web.UI.Control.LoadRecursive() +59
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +678

**Comment by w8tcha** [comment]
What value you put in for MaxRequestLength in the httpruntime section in your web.config?

**Comment by rhunter27338** [comment]
That was the issue.  Under Telerik, the DNN online line documentation sets it to 2GB, but the CK editor can't handle that.  So set everything back to 20MB and everything worked fine.
