### ISSUE TITLE
api key iframely

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#4]
I have trouble getting the iframely code to work, 

I have added it in the DB directly, because I did not find where I could add it in de editor back end: this is my db record (portal 1):

SettingName	SettingValue
DNNCKP#1#embed_provider	//iframe.ly/api/oembed?url={url}&callback={callback}&api_key=54032b8992a03a838e1aa3&iframe=1

see manual: https://iframely.com/docs/ckeditor

The editor keeps telling my, I use the demo version...

Any ideas about what I am missing here?

**Comment by w8tcha** [comment]
Adding the setting directly to the db wouldn't work, only the settings defined in the code are loaded.

I Released version 02.01.09 which includes now the embed_provider setting
https://github.com/w8tcha/dnnckeditor/releases/tag/v02.01.09
