### ISSUE TITLE
Paste as Plain Text Problems

### ISSUE THREAD

**Issue by smbcreativegroup** [w8tcha/dnnckeditor#40]
We have the ckeditor set to force all pasting as plain text. Most of the time this works just fine. Occasionally  chunks of html still end up in the source and break our customers pages. This seems to happen most if someone pastes content that was inside an email. The most common issue is a -1000px left margin being added forcing the entire page to display blank or gray with nothing accessible. With "Force as Plain Text" enabled, why can any code be unintentionally added to the source and how can this be prevented from ever happening again?

**Comment by smbcreativegroup** [comment]
CKEditor HTML Editor Provider V. 2.07 on a DNN 7.4.02 site

But we have seen this occur on many versions.

**Comment by w8tcha** [comment]
Does this issue also occur with the latest version? If yes can you paste here some sample content?

**Comment by smbcreativegroup** [comment]
I am not certain about the latest version. The majority of our customers use the version listed above. In the most recent case, the code that broke the page was as follows. This html was added completely automatically and not stripped when pasted as plain text.

<table style="color: rgb(34, 34, 34); font-family: arial, sans-serif; font-size: 12.8px; width: 1068px;">
 <tbody>
  <tr>
   <td style="margin: 0px;">Their body text was here.</td>
  </tr>
 </tbody>
</table>

Sometimes instead of a table being added, a class is added which is called "MsoNormal" or something similar.

**Comment by w8tcha** [comment]
There is not much i can do. The version you are using is more then 2 years old. And there have been many improvement been done regarding the copy & paste functions in the editor. 

If the issue would still occur with the latest version than the issue would need to be reported to the ckeditor issue tracker
