### ISSUE TITLE
Clear Cache After Upgrade

### ISSUE THREAD

**Issue by smbcreativegroup** [w8tcha/dnnckeditor#42]
After upgrading to the latest version, users are having problems with the html editor loading. They receive a message saying:  “CKEditor is loading….please wait.” And it hangs.

After clearing the local browser cache, it seems to fix the problem.

I have started and stopped the services, recycled the app pool and also cleared the DNN Host cache in an effort to resolve the problem.  Do you have any additional suggestions on how I can eliminate the need for users to have to clear their browser cache?

**Comment by w8tcha** [comment]
No sorry, the only way of forcing to reload the js files is to clear the browser cache. Or Reload the page via Ctrl + F5

**Comment by smbcreativegroup** [comment]
Thank you.
