### ISSUE TITLE
Height must be non negative Error

### ISSUE THREAD

**Issue by chadwixk** [w8tcha/dnnckeditor#44]
I'm using the DNN Announcements module in DNN 9.2.2 and trying to add a new announcement throws this error:

`An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Height must be non negative. Parameter name: value ---> System.ArgumentOutOfRangeException: Height must be non negative. Parameter name: value at System.Web.UI.WebControls.Style.set_Height(Unit value) at System.Web.UI.WebControls.WebControl.set_Height(Unit value) at DNNConnect.CKEditorProvider.CKHtmlEditorProvider.set_Height(Unit value) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e) --- End of inner exception stack trace ---`

I've checked the Editor Height setting in the config section on DNN. It was originally just 200. I tried adding the 'px' (200px), along with a %, etc. to no avail. Any ideas?

![ckeditor](https://user-images.githubusercontent.com/5115308/50988253-462f5580-14c9-11e9-9702-1e192a4b7058.PNG)

**Comment by chadwixk** [comment]
Anyone? I imagine this is an easy issue.

**Comment by chadwixk** [comment]
Bump

**Comment by w8tcha** [comment]
Which version are you using? I can not reproduce this issue with the latest version 2.01.18

**Comment by chadwixk** [comment]
Hi @w8tcha, thanks for responding. Version 2.x? I'm showing CKEditor is versoin 4.5.3. Here is a sample of the CHANGES.md in the DNN\Providers\HtmlEditorProviders\DNNConnect.CKE\js\ckeditor\4.5.3 folder in DNN.

`CKEditor 4 Changelog
====================

## CKEditor 4.5.3

New Features:

* [#13501](http://dev.ckeditor.com/ticket/13501): Added the [`config.fileTools_defaultFileName`](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-fileTools_defaultFileName) option to allow setting a default filen ame for paste uploads.
* [#13603](http://dev.ckeditor.com/ticket/13603): Added support for uploading dropped BMP images.

Fixed Issues:

* [#13590](http://dev.ckeditor.com/ticket/13590): Fixed: Various issues related to the [Paste from Word](http://ckeditor.com/addon/pastefromword) feature. Fixes also:
  * [#11215](http://dev.ckeditor.com/ticket/11215),
  * [#8780](http://dev.ckeditor.com/ticket/8780),
  * [#12762](http://dev.ckeditor.com/ticket/12762).
* [#13386](http://dev.ckeditor.com/ticket/13386): [Edge] Fixed: Issues with selecting and editing images.
* [#13568](http://dev.ckeditor.com/ticket/13568): Fixed: The [`editor.getSelectedHtml()`](http://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-getSelectedHtml) method returns invalid results for entire content selection.
* [#13453](http://dev.ckeditor.com/ticket/13453): Fixed: Drag&drop of entire editor content throws an error.
* [#13465](http://dev.ckeditor.com/ticket/13465): Fixed: Error is thrown and the widget is lost on drag&drop if it is the only content of the editor.
* [#13414](http://dev.ckeditor.com/ticket/13414): Fixed: Content auto paragraphing in a nested editable despite editor configuration.
* [#13429](http://dev.ckeditor.com/ticket/13429): Fixed: Incorrect selection after content insertion by the [Auto Embed](http://ckeditor.com/addon/autoembed) plugin.
* [#13388](http://dev.ckeditor.com/ticket/13388): Fixed: [Table Resize](http://ckeditor.com/addon/tableresize) integration with [Undo](http://ckeditor.com/addon/undo) is broken.

Other Changes:

* [#13637](https://dev.ckeditor.com/ticket/13637): Several icons were refactored.
* Updated [Bender.js](https://github.com/benderjs/benderjs) to 0.3.0 and introduced the ability to run tests via HTTPs ([#13265](https://dev.ckeditor.com/ticket/13265)).

## CKEditor 4.5.2

Fixed Issues:

* [#13609](http://dev.ckeditor.com/ticket/13609): [Edge] Fixed: The browser crashes when switching to the source mode. Thanks to [Andrew Williams and Mark Smeed](http://webxsolution.com/)!
* [PR#201](https://github.com/ckeditor/ckeditor-dev/pull/201): Fixed: Buttons in the toolbar configurator cause form submission. Thanks to [colemanw](https://github.com/colemanw)!
* [#13422](http://dev.ckeditor.com/ticket/13422): Fixed: A monospaced font should be used in the `<textarea>` element storing editor configuration in the toolbar configurator.
* [#13494]`

**Comment by w8tcha** [comment]
I was referring to the Editor Provider version number, not the Editor Version.

But you are using a different Editor Provider not my one. You posted the in the wrong Github Project Page. You need to post your issue here...

https://github.com/DNN-Connect/CKEditorProvider

**Comment by chadwixk** [comment]
@w8tcha ahh, gotcha. Sorry about that! Thank you for pointing me in the right direction.

**Comment by chadwixk** [comment]
Hey @w8tcha .... I switched to use your provider...it still gives the same error.

`An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Height must be non negative. Parameter name: value ---> System.ArgumentOutOfRangeException: Height must be non negative. Parameter name: value at System.Web.UI.WebControls.Style.set_Height(Unit value) at System.Web.UI.WebControls.WebControl.set_Height(Unit value) at DNNConnect.CKEditorProvider.CKHtmlEditorProvider.set_Height(Unit value) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e) --- End of inner exception stack trace ---`

**Comment by chadwixk** [comment]
Finally fixed the error. Changing the height from 99% to 400px in it's default settings worked.
![editor](https://user-images.githubusercontent.com/5115308/51575216-7d5d1980-1e6e-11e9-933c-6e6a9a522e9d.PNG)

**Comment by chadwixk** [comment]
Figured it out. Was a setting in the DNN.Announcements for that module. Somehow it was set to -1. Changed to 400px, works.
![editor](https://user-images.githubusercontent.com/5115308/51575432-4e937300-1e6f-11e9-9ea2-e00bd7fef697.PNG)
