### ISSUE TITLE
Poor performance CKEditor large site

### ISSUE THREAD

**Issue by meffj00** [w8tcha/dnnckeditor#45]
We have DNN platform 9.2.2. , a main site with 11 subsites, installed in our test environment.
The main site contains many hundreds of folders and thousands of files. To read an image from this structure with the CKEditor takes about 1 minute. The second time it goes much faster (15 seconds) with Chrome. In both cases it takes 5 seconds to select the file. The subsites are not affected because they contain far fewer folders and files. Previously with the Telerik editor never suffered. Are you familiar with this or do you know a solution to this problem?

**Comment by w8tcha** [comment]
Yes this is a known issue. But there are no solutions for this issue.

**Comment by w8tcha** [comment]
i think we can close this. Because its a duplicate from #10
