### ISSUE TITLE
Image NOT Selected on New File Upload

### ISSUE THREAD

**Issue by smbcreativegroup** [w8tcha/dnnckeditor#46]
When uploading a new image, the new image is NOT selected by default.

This causes the user to have to search for the file which can be difficult on a large site with many files.

Is there a setting that will make sure the uploaded image is selected by default when the upload process completes?

![image](https://user-images.githubusercontent.com/42415814/54131857-35c02c00-43e1-11e9-915d-07b2ca8fda5f.png)

**Comment by meffj00** [comment]
We have found the same problem in DNN 9.2.2. On sites with many images you have to look up the image again with paging, which takes a lot of time and actions. Actually, e.e.a. is not workable!

**Comment by smbcreativegroup** [comment]
Is it possible for the editor to recognize when only a single file has been uploaded and "select" the file by default?

**Comment by smbcreativegroup** [comment]
Good morning @w8tcha .  Would you be able to provide some input on this topic?  I think it is a valid concern affecting many users.  Thank you in advance for the quality module.  You are appreciated.

**Comment by w8tcha** [comment]
It was working before. I will look in to it. But at the moment i dont have time for it

**Comment by meffj00** [comment]
Hi @w8tcha, as i post before. We have a large site and it's for our users not fine to work with he editor. 
Is there a SettingValue in the CKE_Settings file we'll have to change? What's the SettingName? Thanks!

**Comment by w8tcha** [comment]
The problem is that you can uploaded multiple images. and then selecting all wouldnt work. I dont think there will be a solution for this problem.

**Comment by sleupold** [comment]
Ingo, wouldn't it be possible to check, whether just a single file has been uploaded?
or always picking the first one just being uploaded (from the upload string)?
IMO that would be helpful!

**Comment by w8tcha** [comment]
This would work but this would not solve the problem when paging is enabled

**Comment by smbcreativegroup** [comment]
This would be very helpful to allow if paging is not enabled.

**Comment by meffj00** [comment]
When uploading one file it's not done to select the file after uploading. On large sites this action takes i lot of time and you cannot search for the file! When paging is enabled you don't know on which page the file is been displayed. So i agree with the smbcreativegroup, automatic select
tbe upload file when paging is not enabled! Thank you on behalf of many users.

**Comment by smbcreativegroup** [comment]
@w8tcha are you able to implement some feature to accommodate this issue? 

Either selecting the image if a single file is uploaded.  Or select the first image if multiple images are uploaded and the community knows that this will only work if PAGING is Disabled.

Thank you for any update on this issue.

**Comment by w8tcha** [comment]
issue is fixed with https://github.com/w8tcha/dnnckeditor/releases/tag/v02.01.26

**Comment by smbcreativegroup** [comment]
Thank you for adding this to the new release!
