### ISSUE TITLE
Pagination in editor very annoying

### ISSUE THREAD

**Issue by meffj00** [w8tcha/dnnckeditor#48]
We have a large site with a lots of folders and files. As soon as there are more then 16 files in the CKEditor, a 'pagingcontrol' is active and a page 2, 3  4 etc. is displayed. Browsing through this pages takes a lot of time (7 sec each time) After you have uploaded a file you don't know exactly on which page the file is located. 
Very frustrating to find the right file partly because the uploaded file is not automatically selected. You can't search either. Is it possible to turn off the pagination or raise the number for a page?

**Comment by smbcreativegroup** [comment]
Look in the editor config settings.  I believe there is an area to set the pagination to 0 which removes it.

**Comment by meffj00** [comment]
Thanks, i have found the setting and it works!
