### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by b-creative** [w8tcha/dnnckeditor#49]
Can I just install the latest dnnckeditor provider  (https://github.com/w8tcha/dnnckeditor/releases/latest) on top of an existing DNN 9.2.2 derived CKeditor? (in Extensions > Providers I see version 1.0.4 and in the file structure there's: /Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3) 

Or do I have any prep work?

**Comment by w8tcha** [comment]
Yes you can install the editor as separate installation!

**Comment by b-creative** [comment]
Ok, so it doesn’t replace the one used bij DNN?

**Comment by w8tcha** [comment]
No, it uses different folders. So nothing is replaced.
