### ISSUE TITLE
After Upgrade to 2.1.8, CKEditor loads forever

### ISSUE THREAD

**Issue by sleupold** [w8tcha/dnnckeditor#5]
I upgraded a site (DNN 7.4.2) from CKEditor 2.1.6 to 2.1.8, and now the editor loading donut spins forever.
I tried uninstall (clearing ophaned plugins and themes from /providers section) and re-install, cleared browser cache, disabled all CDN options, but no luck.
Finally, I had to uninstall and re-install 2.1.6

**Comment by w8tcha** [comment]
did you get any js error messages in the browser console?

**Comment by schotman** [comment]
I had the same issue in FF not in chrome

**Comment by schotman** [comment]
It throws errors on various plugin.js: tableresize, mathajax, styelparser, embed, codesnippets, xmltemplates

**Comment by schotman** [comment]
After uninstalling and reinstalling version 2.1.9, the basic problem is the configuration module. It refers to plugins that are no longer included in the distribution, after removing all but dnnpages from the extraplugins box, the editor worked.

**Comment by sleupold** [comment]
Ingo, ich habe CKEditor 2.1.6 neu installiert, aber der Dateibrowser sieht übel aus - in der Konsole sehe ich folgenden Fehler: 
Aktuelles Fenster: test.trans-ocean.org/Providers/HtmlEditorProviders/CKEditor/Browser/Browser.aspx
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(XHR)GET - http://domain.com/Providers/HtmlEditorProviders/CKEditor/Browser/Browser.comb.min.css
In dem Verzeichnis befindet sich auch nur eine Datei Browser.comb.css. Wenn ich die wie angefordert umbenenne, funktioniert es wieder.
 
Den Fehler bei 2.1.8 muss ich noch testen.
Gruß, Sebastian

**Comment by schotman** [comment]
In 2.1.9. I am not  able to add plugin's. I want to add a video plugin: youtube or videodetector. But the icons fail to show up in the menu bar. Followed your instructions to no avail. The icons are added using the configurator, but are not visible in the editor bars (added them to all)

**Comment by sleupold** [comment]
Peter, please use a dedicated issue for your subject, thank you.

**Comment by sleupold** [comment]
I installed CKEditor 2.1.8 on another (older) clone of the site and it behaves as expected, strange.

**Comment by sleupold** [comment]
ok, I finally installed CKEditor 2.1.9 on the site, where 2.1.8 failed as well. I cleared the ckeditor folder prior to installation of the upgrade. The Editor does not load again.
Errors in Browser Console:
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI
(Uniform Resource Identifier) gefunden.
(XHR)GET - http://domain.com/jquery.js
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - http://domain.com/Providers/HtmlEditorProviders/CKEditor/plugins/embed/plugin.js?t=H8DA
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - http://domain.com/Providers/HtmlEditorProviders/CKEditor/plugins/mathjax/plugin.js?t=H8DA
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - http://domain.com/Providers/HtmlEditorProviders/CKEditor/plugins/tableresize/plugin.js?t=H8DA
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - http://domain.com/Providers/HtmlEditorProviders/CKEditor/plugins/stylesheetparser/plugin.js?t=H8DA
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - http://domain.com/Providers/HtmlEditorProviders/CKEditor/plugins/codesnippet/plugin.js?t=H8DA
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
SCRIPT5022: [CKEDITOR.resourceManager.load] Resource name "embed" was not found at "http://domain.com/Providers/HtmlEditorProviders/CKEditor/plugins/embed/plugin.js?t=H8DA".
ckeditor.js (254,74)

**Comment by w8tcha** [comment]
okay looks like i used the wrong build-config to build the editor, now all plugins are included i reuploaded version 2.1.9

**Comment by sleupold** [comment]
ok, I just performed an upgrade from 2.1.6 to the new 2.1.9 and succeeded (though I noticed that the DNN 7 package is nearly 1 MB smaller compared to 2.1.6)

**Comment by w8tcha** [comment]
Yes its smaller because i use now the CKBuilder to build the editor. Which means less js files and most icons of the plugins are loaded as sprites

**Comment by sleupold** [comment]
smaller size seems to be caused by removed skins and plugins.

**Comment by w8tcha** [comment]
no plugins where removed, only old skins

**Comment by sleupold** [comment]
I see the following plugin folders included no longer:
Ajax, autoembed, clipboard, embed, embedsemantic, fakeobjects, iframedialog, kama, language, lineutils, notification, notificationaggregator, stylesheetparser, tableresize, widgetselection, xml, xmltemplates.

**Comment by w8tcha** [comment]
Yes that is correct, but just because the folder are removed doesn't mean that the plugins are removed. All plugins are still included and loaded.

**Comment by sleupold** [comment]
agreed, but the folders are not removed during upgrade.
