### ISSUE TITLE
File browser error

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#50]
Hi Ingo,

I am getting an error in FF and Chrome on DNN931 and CKEditor 2.1.22:

Unable to cast object of type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.FileInfo]' to type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.IFileInfo]'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.FileInfo]' to type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.IFileInfo]'.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.FileInfo]' to type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.IFileInfo]'.]
   WatchersNET.CKEditor.Browser.Browser.GetFiles(IFolderInfo currentFolderInfo) +884
   WatchersNET.CKEditor.Browser.Browser.ShowFilesIn(IFolderInfo currentFolderInfo, Boolean pagerChanged) +273
   WatchersNET.CKEditor.Browser.Browser.Page_Load(Object sender, EventArgs e) +4035
   System.Web.UI.Control.OnLoad(EventArgs e) +106
   System.Web.UI.Control.LoadRecursive() +68
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3785

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3282.0

**Comment by w8tcha** [comment]
Fixed in 02.01.23
