### ISSUE TITLE
Incorrect Jquery Ui Path in Provider Settings

### ISSUE THREAD

**Issue by cklenk** [w8tcha/dnnckeditor#51]
I just installed CKEditor Provider 2.01.22 on DNN 9. I noticed that when I go to CKEditor Provider Settings there is a console error. It's trying to find jquery-ui.min.css. It looks like there is a typo in the file path "/Providers/HtmlEditorProviders/CKEditor/Content/themes/basse/jquery-ui.min.css". It looks like it should just be "base". Looks like a typo :) 

Here is a screenshot of what the provider settings window looks like:
![image](https://user-images.githubusercontent.com/12185742/56817099-dee8a780-6812-11e9-880a-37eb7f4ddaad.png)

Thanks!

**Comment by w8tcha** [comment]
Sorry i forgot to update the downloads. Please re-download the latest version!
