### ISSUE TITLE
File does not get selected when selected in file browser

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#52]
When I select a file in the left window, the page refreshes, but the file is not selected in the url (image 1), consequently the message in image 2 appears

![image](https://user-images.githubusercontent.com/2582737/56879753-6d9b3580-6a5a-11e9-83d1-883d018a74a7.png)

![image](https://user-images.githubusercontent.com/2582737/56879835-b8b54880-6a5a-11e9-8dd5-d82c3f7fd69d.png)

**Comment by meffj00** [comment]
Hoi Peter, i had the same problem. I solved
it to choose another CK provider in the editor options (DNN 9.3.2). Succes!

**Comment by Dan-GW** [comment]
Same issue after I upgraded to fix the file browser issue #50

**Comment by FROCHE38** [comment]
Same issue with latest CKEditor version and DNN 9.3.1 or 9.3.2. Can you please fix it quickly. Thanks

**Comment by w8tcha** [comment]
fixed in v02.01.24

**Comment by schotman** [comment]
This issue is partly fixed. The image gets selected in the background but in the interface it is not reflected:
![image](https://user-images.githubusercontent.com/2582737/57606211-b5e14a00-7568-11e9-8e2a-0522dfb902a8.png)

When selecting a file in image browser the name of the file is not updated, therefore it looks like the file is not selected, but when you click OK, and go back to the editor, the file is selected.

**Comment by w8tcha** [comment]
Yes that is correct. This was removed for performance reasons. The url type no longer show a preview
