### ISSUE TITLE
Selected Folder not indicated and not in view after refresh

### ISSUE THREAD

**Issue by noahbast** [w8tcha/dnnckeditor#53]
One of our clients has a a very large number of folders and subfolders in their site.

After selecting a folder, the scroll position of the list of folders resets to the top and there is no obvious visual indicator for which folder is selected.  This makes it difficult for content editors to navigate the file structure when uploading and selecting images.

Suggestions:
  Scroll the currently selected folder into view after refresh and set a background color for the folder to make it obvious that it is selected.

**Comment by w8tcha** [comment]
Added in CKEditor Provider 2.01.24

**Comment by noahbast** [comment]
The highlighting of the selected folder helps, but it is still hard to find in a large list.

Please add this (or similar) to run after the list is refreshed:
$('#FoldersBox .SelectedFolder')[0].scrollIntoView();
