### ISSUE TITLE
Edge loads quicks css

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#58]
I don't think this is a problem at all, but I thought I should mention it the editor loads the dialog_iequirks.css (in an html5 skin and in the default xcillion skin). Maybe

**Comment by w8tcha** [comment]
I guess there is a reason for this.

**Comment by sleupold** [comment]
Due to the fact, that Edge is not behaving like IE, it should not use any quirks. But this might be an issue of CKEditor, not the provider.

**Comment by w8tcha** [comment]
Edge has also a quirks mode, defined by the doctype declaration. So i dont see any problems here
