### ISSUE TITLE
not able to add plugin's

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#6]
In 2.1.9. I am not able to add plugin's. I want to add a video plugin: youtube or videodetector. But the icons fail to show up in the menu bar. Followed your instructions to no avail. The icons are added using the configurator, but are not visible in the editor bars (added them to all).

**Comment by w8tcha** [comment]
did you save the editor bar after you added the plugin?

**Comment by schotman** [comment]
Yes I did, they are in the toolbar sets xml of the portal root

**Comment by w8tcha** [comment]
okay i try to reproduce what youtube plugin you try to add?

**Comment by schotman** [comment]
this one https://ckeditor.com/addon/youtube and https://ckeditor.com/addon/videodetector

**Comment by w8tcha** [comment]
Okay i found the problem everything is case sensitive so you always need to see the install instructions of plugin for example for the youtbue add 

```xml
<ToolbarButton>
    <ToolbarName>Youtbube</ToolbarName>
    <ToolbarIcon>youtube.png</ToolbarIcon>
  </ToolbarButton>
```
to the CKToolbarButtons.xml and for the videodetector it is...

```xml
<ToolbarButton>
    <ToolbarName>VideoDetector</ToolbarName>
    <ToolbarIcon>videodetector.png</ToolbarIcon>
  </ToolbarButton>
```

**Comment by schotman** [comment]
Thanks

**Comment by schotman** [comment]
Some comments on both plugin's:

- The youtube plugin works really well for responsive, when you add a youtube url. The embed box can also be used for vimeo

- the VideoDetector adds a strange remove button and does not scale well, however the pull request that is not yet into the plugin solves these problems
