### ISSUE TITLE
2.1.9: Edit toolbar not working

### ISSUE THREAD

**Issue by sleupold** [w8tcha/dnnckeditor#7]
in CKEditor Configuration, selecting a toolbar and clicking "edit" does not result in any loading of title or buttons to be edited.
Tested in DNN 7.4.2, CDN usage disabled, Gravity Skin and Container.

**Comment by sleupold** [comment]
oops, it seem to work, but takes lot of time to load.

**Comment by sleupold** [comment]
edit toolbar takes more than 30 seconds to load and there is no visual feedback.

**Comment by w8tcha** [comment]
With what browser does this happens? i can add a loading animation but at least in chrome it only takes a few seconds

**Comment by sleupold** [comment]
with Edge it takes 30 seconds to load a toolbar, to save or cancel.
Firefox is faster, it needs just 12 seconds.
Some kind of an indicator would be helpful.

**Comment by w8tcha** [comment]
okay when i have time i add a spinner. its weird that ff and edge can not handle the js fast enough in chrome its bellow then 2 seconds
