### ISSUE TITLE
2.1.9: URL Popup not properly displayed and working

### ISSUE THREAD

**Issue by sleupold** [w8tcha/dnnckeditor#8]
the popup to add/edit a URL does not take the text and is not properly displayed with tabs.
Script error:
SCRIPT5007: Unable to get property '0' of undefined or null reference
link.js (25,207)

**Comment by w8tcha** [comment]
remove the dnnpages plugin from the list of extraPlugins in the Editor Config Section then the link dialog will work again

**Comment by sleupold** [comment]
thank you Ingo, that worked!
Maybe it would be nice, to remove it within the upgrade procedure.

**Comment by w8tcha** [comment]
no i need to updated the plugin because with that plugin you can select internal dnn pages from within the link dialog

**Comment by sleupold** [comment]
ok, thanks for the info.

**Comment by w8tcha** [comment]
issue is fixed in 02.01.10

**Comment by sleupold** [comment]
thank you very much, Ingo!
