### ISSUE TITLE
CKEditor is loading, please wait...

### ISSUE THREAD

**Issue by thx1200** [w8tcha/dnnckeditor#9]
All I see is "CKEditor is loading, please wait..." and in the debug console I do see an error (below).  I'm running the latest DNN 9.  I noticed the installer only has DNN8 listed (which I used), but on the front page of GitHub, it did indicate DNN 9 was supported.  Am I installing correctly?

Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "tableresize" was not found at "https://www.MyWebSite.com/Providers/HtmlEditorProviders/CKEditor/plugins/tableresize/plugin.js?t=H8DA".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:formatted:5926)
    at f (ckeditor.js:formatted:5790)
    at Array.D (ckeditor.js:formatted:5798)
    at w (ckeditor.js:formatted:5805)
    at ckeditor.js:formatted:5826

**Comment by w8tcha** [comment]
Correct the dnn 8 package can be also used for the dnn 9 installation (as described in the readme.html)

I updated the downloads now the tableresize plugin is included
https://github.com/w8tcha/dnnckeditor/releases/tag/v02.01.09
